version: "3.1"
services:
  mosquitto:
    build: ./mosquitto
    restart: always
    volumes:
      - conf:/conf
      - logs:/var/log
    ports:
    - "1883:1883"
    - "1884:1884"

  odoo_rfid_mqtt:
    build: ./odoo_rfid_mqtt_client
    restart: always
    environment:
      ODOO_HOST: "$ODOO_HOST"
      ODOO_PORT: "$ODOO_PORT"
      ODOO_USER_NAME: "$ODOO_USER_NAME"
      ODOO_PASSWORD: "$ODOO_PASSWORD"
      PGDATABASE: "$PGDATABASE"
      MQTTHOST: "mosquitto"
      MQTTUSER: "$MQTTUSER"
      MQTTPASS: "$MQTTPASS"
      KEY: "$KEY"
    depends_on:
      - mosquitto

networks:
  default:
    driver_opts:
      encrypted: 1

volumes:
  conf:
  logs:


